### ISSUE TITLE
Clean up --intensity_props docs in README

### ISSUE THREAD

**Issue by jmuhlich** [DenisSch/Quantification#44]
The additional properties defined in this tool should be listed more cleanly, e.g. in a bulleted list. Something like this:

----

Additionally the follow extra properties are available:
* `gini_index` A number between 0 and 1, representing how unequally the signal is distributed. See https://en.wikipedia.org/wiki/Gini_coefficient .
* `intensity_median` Median intensity.

For example, to calculate the Gini index and median intensity for all mask regions, specify `--intensity_props gini_index intensity_median`.

**Comment by FloWuenne** [comment]
This Issue can be closed as it was fixed by #43 I believe!
