### ISSUE TITLE
Missing version file

### ISSUE THREAD

**Issue by LukasHats** [DenisSch/Quantification#51]
Currently, we are missing a version file for the CLI argument (see also [here](https://github.com/labsyspharm/quantification/pull/49)). The Version output by the CLI would be necessary to adjust the nf-core [module](https://github.com/nf-core/modules/blob/master/modules/nf-core/mcquant/main.nf), where the version is hardcoded, see also issue [here](https://github.com/nf-core/mcmicro/issues/46)

**Comment by jmuhlich** [comment]
You need to install the package with pip (`pip install -e` while you are working on the package itself). When pip builds the wheel, it will automatically and temporarily install `setuptools_scm` which is the piece that generates the version file based on git tags etc.
